#' Raw data of dates of county and state level mask mandates for United States during the COVID-19 pandemic
#'
#' Includes start and end dates, as well as conditions and sources for county mask mandates.
#' Updates and corrections can be made with the original data source at https://forms.gle/DtUSyvHDj9rj1Akq8.
#'
#' @format A tibble with 3308 observations of 19 variables:
#' \describe{
#'   \item{state_fips} {FIPS code for the state of the observed county}
#'   \item{state_name} {Name of the state of the observed county}
#'   \item{county_fips} {FIPS code for the observed county}
#'   \item{county_name} {Name of the observed county}
#'   \item{county_mask_policy_start} {Start date of the county mask policy}
#'   \item{county_mask_policy_end} {End date of the county mask policy}
#'   \item{county_conditions} {specific conditions of the county mask policy}
#'   \item{county_source} {source for the county mask policy}
#'   \item{county_escalation} {Did the county escalate an exsisiting mandate}
#'   \item{county_defiance} {Is the county publicly defying or refusing to enforce a mandate}
#'   \item{county_edate} {Column generated by STATA of mask mandate start}
#'   \item{state_mask_policy_start}{ Start date of state mask mandate}
#'   \item{state_mask_policy_end} {End date of state mask mandate}
#'   \item{state_conditions} {Conditions of state mask mandate}
#'   \item{state_source} {Source for state mask mandate}
#'   \item{state_edate} {State start date in STATA's date format}
#'   \item{earliest_policy_edate} {The earliest policy in a given county generated using STATA's date function}
#'   \item{county_fips_str} {Duplicated column of county FIPS code}
#'   \item{date_format} {Earliest date in a human readible format.}
#' }
#'
"raw_mandates"
